[tool.black]
line-length = 160
[tool.isort]
profile = "black"
line_length = 160
multi_line_output = 0
# force_single_line = true
# include_trailing_comma = true
# force_grid_wrap = 0
[tool.autoflake]
remove-all-unused-imports = true